netherite-beacons: true
15-layer-beacons: true
replace-beacon-recipe: true
random-creepers: true
buffed-skeletons: true
buffed-spiders: true
teleport-dragon: true
buffed-crystals: true
disallow-pet-sitting: true
untame-on-hit: true
creepers-explode-on-death: true
insta-fall-death: true
increase-hunger: true
nausea-on-consecutive-eating: true
jump-boost-to-enter-portal: true
disallow-rabbit-spawning: true
remove-fletchers: true
golden-apple-wither: true
godapple-to-enter-portal: true
death-by-nausea: true
instant-death-on-dimensional-bed: true
instant-death-on-entity-cramming: true
exponential-breeding: true
teleport-nether-star: true
decrease-item-despawn-time: true
buffed-phantoms: true
remove-bedrock: true
